- name: Collecting Facts
  hosts: all
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  roles:
    - package_manager
    - zsh
    - git
    - vim
    - python
    - hub
    - autojump
    - autoenv
    - ag
    - tmux
    - {role: osx, when: ansible_os_family == "Darwin"}
