- name: Install recommended dependencies for pyenv
  homebrew:
    name:
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
    state: latest

- name: Install python2
  homebrew: name=python state=latest

- name: Install python3
  homebrew: name=python3 state=latest

- name: Install pyenv
  homebrew: name=pyenv state=latest

- name: Install pyenv-virtualenv
  homebrew: name=pyenv-virtualenv state=latest
