
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"


- name: Install Python versions with pyenv
  shell: 'CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install {{item}} --skip-existing'
  args:
    creates: "{{ '~/.pyenv/versions/' + item | expanduser }}"
  with_items: '{{pyenv_global_versions}}'
  tags: pyenv

- name: Set global Python versions with pyenv
  copy:
    content: "system\n{% for version in pyenv_global_versions %}{{ version }}\n{% endfor %}"
    dest: "{{ '~/.pyenv/version' }}"
  tags: pyenv

- name: Check if pytest.ini file exists
  stat: path="{{dotfiles_user_home}}/pytest.ini"
  register: pytest_stat

- name: Back up pytest.ini file
  command: mv ~/pytest.ini ~/pytest.ini.bak
  args:
    creates: "{{dotfiles_user_home}}/pytest.ini"
  when: pytest_stat.stat.exists

- name: Link pytest.ini file
  file:
    src: "{{dotfiles_home}}/roles/python/files/pytest.ini"
    dest: "{{dotfiles_user_home}}/pytest.ini"
    state: link

- name: Install pipx
  tags: pipx
  shell: "PYENV_VERSION=system python3 -m pip install --user pipx && PYENV_VERSION=system python3 -m pipx install pipx"
  args:
    creates: "{{dotfiles_user_home}}/.local/bin/pipx"
