
- include: osx.yml
  when: ansible_os_family == "Darwin"
- include: debian.yml
  when: ansible_os_family == "Debian"

# TODO: Fedora

- name: Install tmuxinator
  gem: name=tmuxinator state=latest
  when: tmux_install_tmuxinator

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{'~/.tmux.conf' | expanduser }}"
    state: link
