# - include: ubuntu.yml
#   when: ansible_os_family == "Ubuntu"

# - include: fedora.yml
#   when: ansible_os_family == "Fedora"

- include: osx.yml
  when: ansible_os_family == "Darwin"

- name: Install Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git
       dest=~/.vim/bundle/Vundle.vim
       update=no

- name: Makes sure snippets directory exists
  file: path="{{ '~/.vim/snippets' | expanduser }}" state=directory

- name: Link all snippet files
  copy: src={{ item }} dest={{ '~/.vim/snippets/' + item | expanduser}}
  with_items:
    - "_.snippets"
    - "python.snippets"
    - "rst.snippets"

- name: Run vim bundle install
  command: vim +BundleInstall +qall
  when: vim_install_plugins
