- name: Install vim
  homebrew: name=vim state=present install_options=with-python3

- name: Install Mac Vim
  homebrew: name=macvim state=present install_options=with-python3
  when: vim_install_macvim
